name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - iunu

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: iunu/gce-github-runner@iunu
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          machine_zone: 'us-central1-c'
          machine_type: 't2d-standard-1'
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2404-lts-amd64
          network: 'runner-net'
          subnet: 'runner-subnet'
          preemptible: true
          actions_preinstalled: false
          no_external_address: true
          shutdown_timeout: 30

  test1:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - name: Job 1 Test 
        run: echo "This runs on the GCE runner VM"

  test2:
    needs: 
      - create-runner
      - test1
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - name: Wait for longer than shutdown timeout
        run: sleep 60 #Give time for runner to shutdown from shutdown timeout

      - name: Job 2 Test
        run: echo "This also runs on the GCE runner VM"
      - uses: iunu/gce-github-runner@iunu
        with:
          command: stop
        if: always()
