name: Test

on:
  workflow_dispatch:
    inputs:
      finish_timeout:
        description: "Shutdown grace period (in seconds) when manually stopped."
        default: 30
        required: false
  push:
    branches:
      - main
      - iunu
    inputs:
      finish_timeout:
        description: "Shutdown grace period (in seconds) when manually stopped."
        default: 30
        required: false

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: iunu/gce-github-runner@iunu
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          machine_zone: 'us-central1-c'
          machine_type: 't2d-standard-1'
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2004-lts
          network: 'runner-net'
          subnet: 'runner-subnet'
          preemptible: true
          actions_preinstalled: false
          no_external_address: true

  test:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - run: echo "This runs on the GCE runner VM"
      - uses: iunu/gce-github-runner@iunu
        with:
          command: stop
          finish_timeout: ${{ inputs.finish_timeout }}
        if: always()